# Generated by Django 2.0.6 on 2019-03-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_game_collectorforeignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='collectorForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
