# Generated by Django 2.0.6 on 2019-03-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_auto_20190306_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='collectorForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameApp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='userForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
