# Generated by Django 2.0.6 on 2019-03-06 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0005_auto_20190306_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
